### ISSUE TITLE
KeyError when downloading a dataset with missing segmentations

### ISSUE THREAD

**Issue by stevensagaert** [segments-ai/segments-ai#68]
Here's the stack trace:

Traceback (most recent call last):
  File "/home/steven.sagaert/python_workspace/FARAD2SORT/FARAD_research/Steven/Active/segments_interface.py", line 94, in <module>
    dataset = fetch_release(dataset_name=dataset_name)
  File "/home/steven.sagaert/python_workspace/FARAD2SORT/FARAD_research/Steven/Active/segments_interface.py", line 28, in fetch_release
    return SegmentsDataset(release,filter_by="REVIEWED", segments_dir=dump_folder)
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/site-packages/segments/dataset.py", line 155, in __init__
    self.load_dataset()
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/site-packages/segments/dataset.py", line 214, in load_dataset
    list(
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/site-packages/segments/dataset.py", line 198, in _load_image
    self.__getitem__(i)
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/site-packages/segments/dataset.py", line 325, in __getitem__
    segmentation_bitmap = self._load_segmentation_bitmap_from_cache(
  File "/home/steven.sagaert/miniconda3/envs/farad/lib/python3.8/site-packages/segments/dataset.py", line 259, in _load_segmentation_bitmap_from_cache
    segmentation_bitmap_url = label["attributes"]["segmentation_bitmap"]["url"]
KeyError: 'segmentation_bitmap'

The solution is to change line 337 in dataset.py to
except (KeyError,TypeError):

**Comment by dbbert** [comment]
Thanks for the bug report, we'll include this fix in the next SDK release. @segments-arnaud FYI
